language: node_js
node_js:
  - 0.12
sudo: false
env:
  global:
    secure: w7NKe4TMqcAPR1PqPRH5CtPYqX8m4BbkRJpVqInCsO4LZq3hFrhesTxl1fo2HLu2HfO3Ny/F9i0QneagJkrdfxoZBoo0Mll/FlPOsv5Loh2Ipk1TG5ObD7pl61/EjYs1//y48cSOxLCXLbGuFrDDWOlIRSuGgP15UhHthcGdQxOyF3NGtxOC0UULKIEcB9YNWkR8hPX9ClBko1s7vzzNbj2VsxnbexW/n1tpT4iXivyaggBL4vo55lvw+9oFslwfRXjet2rRGhcVqAHf2IyeXzEaQLzdN9e8P0X1F8jrhfnNdvZZilm4mvg5/68FYc8XUHpzo0Hgl6aSfwhFLB9bTItPbCAD9jQVwD+BeHSwqWHrQM+ODdwKQpyDv98GpfI0Tl00tAk35YCfCZNFojYvzH+zoASmY6KnxNRUen+uhEkoQG4bvEGR4ctbiml7mXtCefS5orJ0JG4lhusdyaXX+TDehiPDO8UJq1GDY8Z6r7C4Ew64h5+Xj4QLFA0ZIUR0YpbyCkhgBYswxlhMtJPqO9Jh1fj0W7vUnJTNIs5L3KGkBpdFrVgU7rx3y6I7lUhd/q/RTV6080O4+lQTkA7fePcF5mmqcHHG35UD6PsWm0Gx7JD6bhrhj4dXSYMV9P00vILrY5DVpxBrqz+x5D2Kkjhs20uifNPL0w7OBKG9XrM=
branches:
  only: 
    - deploy
addons:
  apt:
    packages:
    - expect
script:
  - '[ "$TRAVIS_BRANCH" == deploy ] && bash ./deploy.sh'
cache:
  directories:
    - hugo_0.15_linux_amd64
