theme = "vienna"

baseurl = "/"
languageCode = "ja-jp"
title = "bells17's Blog"

# Copyright notice. This is displayer in the footer.
copyright = "Copyright (c) 2019, bells17; all rights reserved."

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    # gitlab = "Your GitLab username"
    # linkedin = "Your LinkedIn username"
    # googleplus = "Your Google+ user id"
    # facebook = "Your Facebook username"
    # reddit = "Your Reddit username"
    # hackernews = "Your Hacker News username"
    # keybase = "Your keybase.io username"
    # instagram = "Your Instagram username"
    # Disqus shortname
    # disqus = "Your disqus shortname"
    # Mixpanel API key.
    # mixpanel_api_key = "Your Mixpanel API key"
    # author = "bells17"
    # avatar = "/path/to/avatar"
    # contact = "Your contact link (ex. mailto:foo@example.com)"
    # bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    # subtitle = "bells17's Blog"
    # themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.

		twitter = "bells17_"
    github = "bells17"
		stackoverflow = "5197060"
		# Google Analytics API key.
    ga_api_key = "UA-150092368-1"
